import AsyncStorage from "@react-native-async-storage/async-storage";
import { launchCamera, launchImageLibrary } from 'react-native-image-picker';
import { Alert, ToastAndroid, Modal } from "react-native";
import { DataService } from "./DataService";
import { LocalDatabase } from "./tree_db";
import RNRestart from 'react-native-restart';
import { Strings } from "./Strings";
import ImageResizer from "react-native-image-resizer";
import RNFS from 'react-native-fs';
import ReactNativeForegroundService from '@supersami/rn-foreground-service';
import { shiftTypes } from "../screens/Shifts";
import { DaoClient } from "./db/dao";
const MIN_BATCH_SIZE = 5

const shiftTypesObject = {
    addSapling: 0,
    addImage: 1,
    updatePlot: 2
}

export const addTreeImageModes = {
    addImage: 0,
    editImage: 1,
}

export class Utils {
    static localdb = new LocalDatabase();

    static async getLocalTreeTypesAndPlots() {
        let treeTypes = await this.localdb.getAllTreeTypes();
        let plots = await this.localdb.getAllPlots();
        return { treeTypes, plots };
    }

    static async logException(logs) {
        await this.localdb.logExceptionLocalDB(logs);
        return;
    }

    static async getLogsFromLocalDB() {
        return await this.localdb.getAllLogs();
    }

    static async getShiftsIDLocalDB(upload) {
        if (upload != undefined) {
            return await this.localdb.getShiftsLocalDB(upload);
        }

        return await this.localdb.getAllShiftID();
    }

    static async getShiftsLive() {
        const shifts = await this.localdb.getAllShiftsLive();
        //console.log("------------live shifts return-----------", shifts , shifts.length)
        return shifts
    }

    static async deleteLogsFromLocalDB() {
        await this.localdb.deleteAllLogs();
    }

    static async syncLogs() {
        const logs = await Utils.getLogsFromLocalDB();
        const response = await DataService.uploadLogs(logs);
        return response;
    }



    static async fetchSaplingIdsFromLiveDB() {
        let saplings = await this.localdb.getAllSaplingsInLiveDB();
        return saplings;
    }

    static async deleteTreeImages(saplingId) {
        //deleting previous images
        await this.localdb.deleteTreeImages(saplingId);
    }

    static async deleteTreeAndImages(saplingId) {
        await this.localdb.deleteTreeImages(saplingId);
        await this.localdb.deleteTree(saplingId);
    }

    static async deleteAddTreeImagesBySaplingId(saplingID) {
        await this.localdb.deleteAddTreeImagesBySaplingId(saplingID)
    }

    static async deleteSaplingShiftLocalDB(saplingId, shiftID) {
        await this.localdb.deleteSaplingShiftDB(saplingId, shiftID);
    }

    static async fetchLocalTree(saplingId) {
        const results = await this.localdb.getTreeBySaplingID(saplingId);
        //console.log("result---" , results);
        if (results.length > 0) {
            return await this.formatLocalTreeToJSON(results[0]);
        }
        return null;
    }

    static async fetchLocalTreeImage(saplingId) {
        console.log("fetching for sapling--", saplingId);
        const results = await this.localdb.getTreeImageBySaplingID(saplingId);
        return results[0];
    }

    static async updateSaplingInShiftDB(newSaplingId, inSaplingId, shiftID) {
        await this.localdb.updateSaplingLocalShiftDb(newSaplingId, inSaplingId, shiftID);
    }

    static async deleteSaplingInShiftDB(sapling_id, shiftID) {
        await this.localdb.deleteSaplingInShiftDB(sapling_id, shiftID);
    }

    static async checkSaplinginUpdatePlotDB(saplingid) {
        console.log("sapling---", saplingid);
        return await this.localdb.checkSaplingUpdatePlotDB(saplingid);
    }

    static async saveUpdatePlot(treeData) {
        await this.localdb.saveUpdatePlots(treeData);
    }

    static async saveNewImage(tree) {
        await this.localdb.saveImage(tree, 0);
    }

    static async deleteSaplingUpdatePlotDB(saplingid) {
        await this.localdb.deleteSaplingUpdatePlotDB(saplingid)
    }

    static async saveShiftsToLocalDB(shiftData) {
        const shiftid = await this.localdb.saveShifts(shiftData);
        console.log("shiftid autogenerated---", shiftid);
        return shiftid;
    }

    static async deleteShiftLocalDB(id) {
        await this.localdb.deleteShiftLocalDB(id);
    }

    static async saveTreeAndImagesToLocalDB(tree, images) {
        console.log("--------------updating image------------------", tree)
        await this.localdb.saveTree(tree, 0);

        for (let index = 0; index < images.length; index++) {
            //console.log("image while adding tree: ", images[index].data)
            const element = {
                sapling_id: tree.sapling_id,
                image: images[index].data,
                image_id: images[index].name,
                remark: images[index].meta.remark,
                timestamp: images[index].meta.capturetimestamp,
            };
            await this.localdb.saveTreeImages(element);
        }
    }

    static async getAppRootTag() {
        return Number.parseInt(await AsyncStorage.getItem(Constants.appRootTagKey));
    }
    // Function to force reload the app
    static async reloadApp() {
        RNRestart.restart();
    }

    static async confirmAction(onConfirm, title = undefined, message = undefined) {
        if (!title) {
            title = Strings.alertMessages.ConfirmActionTitle;
        }
        if (!message) {
            message = Strings.alertMessages.ConfirmActionMsg;
        }
        Alert.alert(title, message, [
            {
                text: Strings.alertMessages.Yes,
                onPress: () => onConfirm()
            },
            {
                text: Strings.alertMessages.No,
                onPress: () => null
            }
        ])
    }

    static async fetchTreesWithNewImage(uploaded) {
        let res;
        if (uploaded !== undefined) {
            res = await this.localdb.getTreesWithNewImage(uploaded);
            //console.log("----------------unuploaded trees with images------------",res)

        } else {
            res = await this.localdb.getAllTreesWithNewImage();
        }

        let final = [];

        for (let index = 0; index < res.length; index++) {
            //console.log("-------------res[index]---------------",res[index])
            let tree = {
                sapling_id: res[index].sapling_id,
                uploaded: res[index].uploaded,
                user_id: res[index].user_id,
                lat: res[index].lat,
                lng: res[index].lng,
                inActive: res[index].inActive,
                image: {
                    name: res[index]?.image_id,
                    data: res[index]?.image,
                    meta: {
                        remark: res[index]?.remark?.replace("''", "'"),
                        capturetimestamp: res[index].timestamp,
                    },
                }
            }
            final.push(tree);
        }

        return final;

    }



    static getShiftID(shifts) {
        // Get the current date and time
        const currentDate = new Date();

        // Extract the year, month, day, hour, minute, and second components from the current date and time
        const year = currentDate.getFullYear();
        const month = String(currentDate.getMonth() + 1).padStart(2, '0'); // Months are zero-based, so add 1
        const day = String(currentDate.getDate()).padStart(2, '0');
        const hour = String(currentDate.getHours()).padStart(2, '0');
        const minute = String(currentDate.getMinutes()).padStart(2, '0');

        // Combine the year, month, day, hour, minute, and second components to form a date-time string
        const dateTimeString = `${year}-${month}-${day}_${hour}:${minute}`;



        // Create the shiftID by concatenating 'shift', the value of shifts + 1, and the date-time string
        const shiftID = `shift${shifts + 1}_${dateTimeString}`;
        //console.log("shiftID---utils--", shiftID);
        return shiftID;
    }

    static formatTime(seconds) {
        //console.log("seconds----", seconds);
        const minutes = Math.floor(seconds / 60);
        const remainingSeconds = seconds % 60;

        if (minutes >= 60) {
            const hours = Math.floor(minutes / 60);
            const remainingMinutes = minutes % 60;
            return `${hours}h ${remainingMinutes}m ${remainingSeconds}s`;
        }

        return `${minutes}m ${remainingSeconds}s`;
    }

    static getCurrentTime12Hr() {
        const date = new Date();
        let hours = date.getHours();
        let minutes = date.getMinutes();
        const ampm = hours >= 12 ? 'PM' : 'AM';

        // Convert hours to 12-hour format
        hours = hours % 12;
        hours = hours ? hours : 12; // Handle midnight (0 hours)

        // Add leading zero to single-digit minutes
        minutes = minutes < 10 ? '0' + minutes : minutes;

        // Construct the 12-hour time string
        const time12Hr = hours + ':' + minutes + ' ' + ampm;

        return time12Hr;
    }

    static async createLocalTablesIfNeeded() {
        // await this.localdb.deleteTables();
        // await AsyncStorage.multiRemove([
        //     Constants.lastHashKey,
        //     Constants.lastHashForShifts,
        //     Constants.adminIdKey,
        //     Constants.appRootTagKey,
        //     Constants.syncDateKey,
        // ])
        const daoClient = await DaoClient.authenticate();
        await daoClient.trees.createTable();
        await daoClient.users.createTable();
        await daoClient.treeImages.createTable();
        await daoClient.plots.createTable();
        await daoClient.sites.createTable();
        await this.localdb.createTreetTypesTbl();
        await this.localdb.createPlotTbl();
        await this.localdb.createSaplingTbl();
        await this.localdb.createTreesTable();
        await this.localdb.createLogsTable();
        await this.localdb.createSaplingPlotTbl();
        await this.localdb.createShiftTblLive();
        await this.localdb.createNewImageTable();
    }

    static async deleteUpdateTreesPlots(sapling_id) {
        await this.localdb.deleteUpdateTreesPlots(sapling_id);
    }

    static async fetchAndStoreHelperData() {
        console.log('fetching helper data in Utils');
        // console.log('ldb: ', this.localdb)
        let lastHash = await AsyncStorage.getItem(Constants.lastHashKey);
        lastHash = String(lastHash);//take care of null values.
        let userId = await Utils.getUserId();
        console.log('requesting: ', userId, lastHash)
        //setStatus(requesting)

        const helperData = await DataService.fetchHelperData(userId, lastHash);

        console.log("userId ", userId, "lastHash ", lastHash)

        if (!helperData) {
            ToastAndroid.show(Strings.alertMessages.UnableToFetchHelperData, ToastAndroid.LONG)
            return ({ helperDataUptoDate: true });
        }

        const data = helperData.data['data'];
        const newHash = helperData.data['hash'];
        console.log("newHash ", newHash)
        if (newHash == lastHash) {
            console.log("---------------------------newHash == lastHash-------------")
            // ToastAndroid.show(Strings.alertMessages.DataUptodate, ToastAndroid.LONG)
            // setStatus(Data updated)
            return ({ helperDataUptoDate: true });
        }
        if (data) {
            console.log("---------------------------New Data-------------")

            await Utils.storeTreeTypes(data['plant_types']);
            await Utils.storePlots(data['plots']);
            console.log("data['sapling_ids'] :", data['sapling_ids'].length)
            await Utils.storeTrees(data['sapling_ids'])
            await AsyncStorage.setItem(Constants.lastHashKey, newHash);
            // ToastAndroid.show(Strings.alertMessages.DataUptodate, ToastAndroid.LONG)
            // setstatus(data updated)
            return ({ helperDataUptoDate: true });
        }
        // setstatus(failed)
    }

    static async fetchAndStoreShifts() {
        let lastHashForShifts = await AsyncStorage.getItem(Constants.lastHashForShifts);
        lastHash = String(lastHashForShifts);
        let userId = await Utils.getUserId();
        userId = parseInt(userId);
        const shiftData = await DataService.fetchShifts(userId, lastHash);

        console.log("lastHash shift---", lastHash)

        if (!shiftData) {
            ToastAndroid.show(Strings.alertMessages.UnableToFetchHelperData, ToastAndroid.LONG)
            return;
        }

        const shiftsForCurrentUser = shiftData.data['data'];
        const newHash = shiftData.data['hash'];
        console.log("newHash shift---", newHash);
        if (newHash == lastHash) {
            console.log("------------------Previous shifts ---- == ----current shifts---------")
            ToastAndroid.show(Strings.alertMessages.ShiftDataUptodate, ToastAndroid.LONG)
            return;
        }

        if (shiftsForCurrentUser) {
            console.log("---------------------------New Shifts-------------")
            await Utils.storeShifts(shiftsForCurrentUser);
            console.log("shiftsForCurrentUser :", shiftsForCurrentUser.length)
            await AsyncStorage.setItem(Constants.lastHashForShifts, newHash);
            ToastAndroid.show(Strings.alertMessages.ShiftDataUptodate, ToastAndroid.LONG)
            return;
        }
        console.log("--------------shiftsForCurrentUser---------", shiftsForCurrentUser.data)
    }

    static async deleteSyncedShiftsBasedOnSaplings(shifts) {
        console.log("-------------type of shifts-------------", shifts)
        await this.localdb.deleteSyncedShifts(shifts)
    }

    static async deletePlotSaplings() {
        await this.localdb.deletePlotSaplings();
    }

    static async checkIfSaplingExistsLocally(sapling) {
        let ifExists = await this.localdb.checkIfSaplingExistsLocally(sapling);
        return ifExists
    }

    static async checkIfSaplingExistsInLiveDB(sapling) {
        let ifExists = await this.localdb.checkIfSaplingExistsInLiveDB(sapling);
        return ifExists
    }

    static async checkIfImageAddedAlready(sapling) {
        let ifExists = await this.localdb.checkIfImageAddedAlready(sapling)
        return ifExists

    }
    static async checkShiftsComplete() {
        try {
            const shifts = await Utils.getShiftsIDLocalDB();
            //console.log("shift got---", shifts);
            for (const shift of shifts) {
                const saplings = JSON.parse(shift?.saplings || '[]');
                //console.log("checkShiftsComplte----", saplings);

                if (saplings.length === 0) {
                    //delete the shift for this id
                    await this.localdb.deleteShiftLocalDB(shift.id);
                    continue;
                }

                if (shift.shiftended == 0) {
                    //check if saplings are uploaded make the shiftended = 1 and shiftupdloadcomplete = 1
                    let uploadedShift = true;
                    for (const sapling of saplings) {
                        if (sapling.uploaded == 0) {
                            uploadedShift = false;
                            break;
                        }
                    }

                    const shiftData = {
                        id: shift.id,
                        user_id: shift.user_id,
                        plot_selected: shift.plotselected,
                        start_time: shift.starttime,
                        end_time: shift.endtime,
                        shift_ended: 1, //made it 1
                        shift_upload_complete: uploadedShift ? 1 : 0,
                        time_taken: shift.timetaken,
                        trees_planted: shift.treesplanted,
                        saplings: saplings
                    }

                    //console.log("final shift data from home screen---", shiftData);

                    await Utils.saveShiftsToLocalDB(shiftData);
                }

            }
        } catch (error) {
            console.log("happened while checking for shiftended(inside Utils)", error);
            const stackTrace = error.stack;
            const errorLog = {
                msg: "happened while checking for shiftended(inside Utils)",
                error: JSON.stringify(error),
                stackTrace: stackTrace
            }
            await this.logException(JSON.stringify(errorLog));
        }
    }

    static async getPlotSaplings(plotId) {
        console.log('getting plot saplings for ', plotId);
        const saplings = await this.localdb.getSaplingsforPlot(plotId);
        console.log(`# saplings : `, saplings.length);
        if (saplings.length > 0) {
            console.log('example: ', saplings[0]);
        }
        return saplings;
    }


    static async storeTreeTypes(plantTypes) {
        // console.log(treeTypes[0])
        const treeTypesInLocalDBFormat = plantTypes.map((plantType) => {
            if (plantType.name) {
                plantType.name = plantType.name.replace("'", "''");
            }
            return {
                name: plantType.name,
                plant_type_id: plantType.plant_type_id,
                id: plantType.id,
            }
        })
        let failure = false;
        for (let dbTreeType of treeTypesInLocalDBFormat) {
            try {
                await this.localdb.updateTreeTypeTbl(dbTreeType);
            }
            catch (error) {
                console.log('Failed to save treeType: ', dbTreeType);
                failure = true;
                const stackTrace = error.stack;
                const errorLog = {
                    msg: "happened while trying to save treeType(inside Utils)",
                    error: JSON.stringify(error),
                    stackTrace: stackTrace
                }
                await this.logException(JSON.stringify(errorLog));
            }
        }
        if (failure) {
            ToastAndroid.show(Strings.alertMessages.FailureSavingTrees);
        }
        else {
            console.log('All tree types saved successfully.')
        }
    }

    static async storePlots(plots) {
        // console.log(plots[0])
        const plotsInLocalDBFormat = plots.map((plot) => {
            if (plot.name) {
                plot.name = plot.name.replace("'", "''");
            }
            return {
                id: plot.id,
                name: plot.name,
                plot_id: plot.plot_id
            }
        })
        let failure = false;
        for (let dbPlot of plotsInLocalDBFormat) {
            try {
                await this.localdb.updatePlotTbl(dbPlot);
            }
            catch (error) {
                console.log('Failed to save plot: ', dbPlot);
                console.log(error);
                failure = true;
                const stackTrace = error.stack;
                const errorLog = {
                    msg: "happened while trying to save plot(inside Utils)",
                    error: JSON.stringify(error),
                    stackTrace: stackTrace
                }
                await this.logException(JSON.stringify(errorLog));
            }
        }
        if (failure) {
            ToastAndroid.show(Strings.alertMessages.FailureSavingPlots);
        }
        else {
            console.log('All plots saved successfully.')
        }
    }


    //store all trees - Namrata
    static async storeTrees(saplingsDocs) {

        const treesInLocalDBFormat = saplingsDocs.map((doc) => {
            return {
                saplingid: doc.sapling_id,
            }
        })
        let failure = false;
        console.log("length in storeTrees : ", treesInLocalDBFormat.length)

        try {
            await this.localdb.updateSaplingTbl(treesInLocalDBFormat);

        }
        catch (error) {
            console.log('Failed to save saplings : ', error);
            failure = true;
            const stackTrace = error.stack;
            const errorLog = {
                msg: "happened while trying to save saplings(inside Utils)",
                error: JSON.stringify(error),
                stackTrace: stackTrace
            }
            await this.logException(JSON.stringify(errorLog));
        }


        if (failure) {
            ToastAndroid.show(Strings.alertMessages.FailureSavingSaplings);
        }
        else {
            console.log('All saplings saved successfully.')
        }
    }

    static async storeShifts(shifts) {
        //console.log("----------------shifts-------------",shifts)
        const shiftsInLocalDBFormat = shifts.map((shift) => {
            if (shift.plot_selected) {
                shift.plot_selected = shift.plot_selected.replace("'", "''");
            }
            shift.saplings.map((sapling) => {
                sapling.uploaded = 1;
            })
            return {
                plot_selected: shift.plot_selected,
                end_time: shift.end_time,
                saplings: shift.saplings,
                shift_id: shift.id,
                shift_type: shift.shift_type,
                start_time: shift.start_time,
                timestamp: shift.timestamp,
                time_taken: shift.time_taken,
                trees_planted: shift.trees_planted,
                user_id: shift.user_id,
                shift_ended: 1,
                shift_upload_complete: 1,
            }
        })

        let failure = false;
        await this.localdb.deleteShiftTblLive(); //empty the table and add latest data.

        for (let shift of shiftsInLocalDBFormat) {
            try {
                await this.localdb.updateShiftTblLive(shift);
            }
            catch (error) {
                console.log('Failed to save shift: ', shift);
                console.log(error);
                failure = true;
                const stackTrace = error.stack;
                const errorLog = {
                    msg: "happened while trying to save shift(inside Utils)",
                    error: JSON.stringify(error),
                    stackTrace: stackTrace
                }
                await this.logException(JSON.stringify(errorLog));
            }
        }
        if (failure) {
            ToastAndroid.show(Strings.alertMessages.FailureSavingPlots);
        }
        else {
            console.log('All shifts saved successfully.')
        }
    }

    static async deleteSyncedTreesAndImages() {
        let newTreesList = await this.localdb.deleteSyncedTrees();
        let unuploadedImageTrees = await this.localdb.deleteSyncedImageTrees();
        await this.localdb.deleteUpdateTreesPlots();
        //console.log("-----------------unuploadedImageTrees-------------", unuploadedImageTrees[1].sapling_id)
        newTreesList = await Promise.all(newTreesList.map(async (tree) => {
            return await Utils.formatLocalTreeToJSON(tree);
        }))

        return newTreesList;
    }

    static getDisplayString = (index, capturetimestamp, length) => {
        const indexString = `(${index + 1} of ${length})\n`;
        const captureString = Strings.messages.CapturedAt + ' :\n' + Utils.getReadableDate(capturetimestamp);
        const displayString = `${indexString} ${captureString}`;
        return displayString;
    }

    static getReadableDate(date) {//string arg
        const epochMilliseconds = Date.parse(date);
        if (isNaN(epochMilliseconds)) {
            return date;
        }
        const dateObj = new Date(date);
        const dateStr = dateObj.toDateString().split(' ').slice(1).join(' ');//remove day
        const timeStr = dateObj.toTimeString().split(':').slice(0, -1).join(':');//remove seconds
        return dateStr + ', ' + timeStr;
    }


    static async fetchTreesWithNewPlot(upload) {
        let res;
        if (upload !== undefined) {
            res = await this.localdb.getTreesWithNewPlots(upload);

        } else {
            res = await this.localdb.getAllTreesWithNewPlots();
        }
        return res;
    }

    static async getTreesCounts() {
        const pendingTrees = (await Utils.fetchTreesFromLocalDB(0)).length;
        const uploadedTrees = (await Utils.fetchTreesFromLocalDB(1)).length;

        const treesWithNewImages = (await Utils.fetchTreesWithNewImage(0)).length;
        const uploadedImages = (await Utils.fetchTreesWithNewImage(1)).length;

        //for trees With New Plot
        const pendingTreesPlots = (await Utils.fetchTreesWithNewPlot(0)).length;
        const uploadedTreesPlots = (await Utils.fetchTreesWithNewPlot(1)).length;

        const pending = {
            treesUpload: pendingTrees,
            plotUpload: pendingTreesPlots,
            imagesUpload: treesWithNewImages
        }

        return { pending, uploaded: uploadedTrees + uploadedTreesPlots + uploadedImages };
    }

    static async getShiftsCounts() {
        const pending = (await Utils.getShiftsIDLocalDB(0)).length;
        const uploaded = (await Utils.getShiftsIDLocalDB(1)).length;
        return { pending, uploaded };
    }

    static async fetchTreesAddSaplings() {
        let res = await this.localdb.getAllTrees();
        return res;
    }

    static async syncShifts(onProgress = undefined) {
        let shifts = await Utils.getShiftsIDLocalDB(0); //not uploaded.

        for (const shift of shifts) {
            const shiftType = shiftTypesObject[shift.shift_type];
            let saplingsInShift = shift.saplings;
            let saplingsFromLocalTable;

            if (shiftType === shiftTypes.addSapling) {
                saplingsFromLocalTable = await Utils.fetchTreesAddSaplings();
            } else if (shiftType === shiftTypes.addImage) {
                saplingsFromLocalTable = await Utils.fetchTreesWithNewImage();
            } else if (shiftType === shiftTypes.updatePlot) {
                saplingsFromLocalTable = await Utils.fetchTreesWithNewPlot(0)
            }

            //console.log(shiftType, "saplingsFromLocalTable---", saplingsFromLocalTable);

            saplingsInShift = saplingsInShift.filter(saplingId => {
                for (const sapling of saplingsFromLocalTable) {
                    if ((sapling.sapling_id === saplingId.sapling_id && sapling.uploaded === 0)) {
                        console.log("here---", sapling.sapling_id, saplingId.sapling_id, sapling.uploaded);
                        //skip this sapling don't add to saplingsInShift and continue the loop 
                        return false;
                    }
                }
                return true;

            });

            console.log("filtered saplingsInShift---", saplingsInShift);
            shift.saplings = saplingsInShift;
        }

        shifts = shifts.filter(item => item.saplings && item.saplings.length > 0);

        console.log("filtered shifts to sync", shifts);


        const failures = [];
        let shiftResponse;

        if (shifts.length === 0) {
            return { shiftDetails: null, failures: failures };
        }

        for (let i = 0; i < shifts.length; i += MIN_BATCH_SIZE) {
            shiftResponse = await Utils.batchUploadShifts(shifts.slice(i, i + MIN_BATCH_SIZE));
            console.log("shiftResponse---", shiftResponse);
            let batchFailures = shiftResponse.failures;
            failures.push(...batchFailures);
            if (onProgress) {
                onProgress(i / shifts.length);
            }
        }

        console.log("failed shifts---", failures, shiftResponse);
        await Utils.setLastSyncDateNow();

        // if (failures.length === 0) {
        //     Alert.alert(Strings.alertMessages.SyncSuccess, Strings.alertMessages.CheckLocalList);
        // }
        // else {
        //     //change to sync failure for sync
        //     Alert.alert(Strings.alertMessages.SyncFailureForShifts, Strings.alertMessages.ContactExpert);
        // }

        return { shiftDetails: shiftResponse.response, failures: failures };
    }

    static async batchUploadShifts(batch) {
        let failures = batch;
        let response
        try {
            response = await DataService.uploadShifts(batch);
            if (response) {
                failures = await Utils.setShiftsSyncStatus(response, batch);
            }
        }
        catch (error) {
            console.error(error);
            const stackTrace = error.stack;
            const errorLog = {
                msg: "happened while trying to batchUploadShifts(inside Utils)",
                error: JSON.stringify(error),
                stackTrace: stackTrace
            }
            await this.logException(JSON.stringify(errorLog));
        }
        console.log("response after batchUploadShifts---", response);
        return { response: response, failures: failures };
    }

    static async setShiftsSyncStatus(statuses, shifts) {
        const failures = [];
        for (let shift of shifts) {
            let uploadedSaplings = shift.saplings
            const id = statuses[shift.id];
            if (id && id.shiftUploaded) {
                await this.localdb.updateShiftUpload(shift.id, id.shiftID, uploadedSaplings);
            }
            else {
                failures.push(shift.id);
            }
        }

        return failures;
    }

    static async setImagesSyncStatus(statuses, batch) {
        const failures = [];
        for (let tree of batch) {
            const status = statuses[tree.sapling_id];
            if (status && status.dataUploaded) {
                await this.localdb.updateSaplingImageUpload(tree.sapling_id);
            }
            else {
                failures.push(tree.sapling_id);
                //delete the failed sapling from local db and local shift db

            }
        }
        return failures;

    }

    static async updateTreesWithChangedPlot(plot_id, shiftID) {
        try {
            await this.localdb.updateTreesWithChangedPlot(plot_id, shiftID)
        } catch (error) {
            console.log("---------error while updating plot in local trees--------", error);
        }
    }

    static async updateTreesWithChangedPlotInPlotsTable(old_plot, new_plot, shiftID) {
        try {
            await this.localdb.updateTreesWithChangedPlotInPlotsTable(old_plot, new_plot, shiftID)
        } catch (error) {
            console.log("---------error while updating plot in local trees--------", error);
        }
    }

    static async changeShiftPlot(plotName, shiftID) {
        try {
            await this.localdb.changeShiftPlot(plotName, shiftID)
        }
        catch (error) {
            console.log("---------error while updating plot in shift Tbl--------", error);
        }
    }

    static async batchUploadImages(batch) {
        let failures = batch;
        try {
            let response = await DataService.uploadNewImages(batch);
            if (response) {
                failures = await Utils.setImagesSyncStatus(response, batch);
            }
        }
        catch (error) {
            console.error(error);
            const stackTrace = error.stack;
            const errorLog = {
                msg: "happened while trying to batchUploadImages(inside Utils)",
                error: JSON.stringify(error),
                stackTrace: stackTrace
            }
            await this.logException(JSON.stringify(errorLog));
        }
        //console.log("failed upload response: ---", failures);
        return failures;
    }

    static async batchPlotUpload(batch) {
        let failures = batch;
        // console.log("batch before sync---", batch);

        try {
            let response = await DataService.uploadTreesNewPlot(batch);
            console.log("response from uploadPlots: ", response);
            if (response) {
                failures = await Utils.setTreePlotSyncStatus(response, batch);
                //console.log('batch failures: ', failures);
            }
        }
        catch (error) {
            console.error(error);
            const stackTrace = error.stack;
            const errorLog = {
                msg: "happened while trying to batchPlotUpload(inside Utils)",
                error: JSON.stringify(error),
                stackTrace: stackTrace
            }
            await this.logException(JSON.stringify(errorLog));
        }
        console.log("failed upload response: ---", failures);
        return failures;
    }

    static async batchUpload(batch) {
        let failures = batch;
        console.log("batch before sync---", batch);
        try {
            let response = await DataService.uploadTrees(batch);
            console.log("response from uploadTrees: ", response);
            if (response) {
                failures = await Utils.setTreeSyncStatus(response, batch);
                //console.log('batch failures: ', failures);
            }
        }
        catch (error) {
            console.error(error);
            const stackTrace = error.stack;
            const errorLog = {
                msg: "happened while trying to batchUpload(inside Utils)",
                error: JSON.stringify(error),
                stackTrace: stackTrace
            }
            await this.logException(JSON.stringify(errorLog));
        }
        //console.log("failed upload response: ---", failures);
        return failures;
    }

    static async setLastSyncDateNow() {
        const currentTime = new Date().toString();
        await AsyncStorage.setItem(Constants.syncDateKey, currentTime);
    }
    static async getLastSyncDate() {
        return await AsyncStorage.getItem(Constants.syncDateKey);
    }

    static async upload(onProgress = undefined) {
        const final = await Utils.fetchTreesFromLocalDB(0);//not uploaded.
        const failures = [];
        for (let i = 0; i < final.length; i += MIN_BATCH_SIZE) {
            const batchFailures = await Utils.batchUpload(final.slice(i, i + MIN_BATCH_SIZE));
            failures.push(...batchFailures);
            if (onProgress) {
                onProgress(i / final.length);
            }
        }
        await Utils.setLastSyncDateNow();
        console.log("failed upload: ---", failures);
        if (failures.length === 0) {
            Alert.alert(Strings.alertMessages.SyncSuccess, Strings.alertMessages.CheckLocalList);
        }
        else {
            Alert.alert(Strings.alertMessages.SyncFailureForTrees, Strings.alertMessages.ContactExpert);
        }
        const finalSaplingIds = final.map(item => item.sapling_id);
        const uploadedSaplings = finalSaplingIds.filter(sapling_id => !failures.includes(sapling_id));
        return { failures: failures, uploadedSaplings: uploadedSaplings };
    };

    static async uploadNewImages(onProgress = undefined) {
        const final = await Utils.fetchTreesWithNewImage(0);//not uploaded.
        //console.log("--------------------final-uploadNewImages--------------", typeof final[0].image);
        const failures = [];
        for (let i = 0; i < final.length; i += MIN_BATCH_SIZE) {
            const batchFailures = await Utils.batchUploadImages(final.slice(i, i + MIN_BATCH_SIZE));
            failures.push(...batchFailures);
            if (onProgress) {
                onProgress(i / final.length);
            }
        }
        await Utils.setLastSyncDateNow();

        if (failures.length === 0) {
            Alert.alert(Strings.alertMessages.SyncSuccess, Strings.alertMessages.CheckLocalList);
        }
        else {
            Alert.alert(Strings.alertMessages.SyncFailureForImages, Strings.alertMessages.ContactExpert);
        }
        const finalSaplingIds = final.map(item => item.sapling_id);
        const uploadedImageSaplings = finalSaplingIds.filter(sapling_id => !failures.includes(sapling_id));
        return { failures: failures, uploadedImageSaplings: uploadedImageSaplings };
    };


    static async uploadTreesPlots(onProgress = undefined) {
        const final = await Utils.fetchTreesWithNewPlot(0);//not uploaded.
        const failures = [];

        for (let i = 0; i < final.length; i += MIN_BATCH_SIZE) {
            const batchFailures = await Utils.batchPlotUpload(final.slice(i, i + MIN_BATCH_SIZE));
            failures.push(...batchFailures);
            if (onProgress) {
                onProgress(i / final.length);
            }
        }


        await Utils.setLastSyncDateNow();
        console.log("failed upload: ---", failures);
        if (failures.length === 0) {
            Alert.alert(Strings.alertMessages.SyncSuccess, Strings.alertMessages.CheckLocalList);
        }
        else {
            Alert.alert(Strings.alertMessages.SyncFailure, Strings.alertMessages.ContactExpert);
        }

        const finalSaplingIds = final.map(item => item.sapling_id);
        const failedMessages = failures.map(item => item.message);
        console.log("-----------failures-----------", failures)
        const failedSaplingIds = failures.map(item => item.sapling_id);
        const uploadedSaplings = finalSaplingIds.filter(sapling_id => !failedSaplingIds.includes(sapling_id));

        // Check if any failedMessages contains undefined
        const hasUndefinedMessages = failedMessages.some(message => message === undefined);

        return { failures: hasUndefinedMessages ? failures : failedMessages, uploadedSaplings: uploadedSaplings };
    };


    static userId;
    static adminId;
    static localdb;
    // static lang;

    static async setTreePlotSyncStatus(statuses, batch) {
        const failures = [];
        for (let tree of batch) {
            const status = statuses[tree.sapling_id];
            if (status && status.dataUploaded) {
                await this.localdb.updateTreePlotUpload(tree.sapling_id);
            }
            else {
                failures.push({
                    sapling_id: tree.sapling_id,
                    message: status.message
                });
            }
        }
        return failures;
    }

    static async setTreeSyncStatus(statuses, batch) {
        const failures = [];
        for (let tree of batch) {
            const status = statuses[tree.sapling_id];
            if (status && status.dataUploaded) {
                await this.localdb.updateUpload(tree.sapling_id);
            }
            else {
                failures.push(tree.sapling_id);
            }
        }
        return failures;

    }

    static async fetchSaplingsFromLiveShiftDB(id) {
        let res = await this.localdb.getSaplingsInLiveShifts(id);
        let saplingArray = res.saplingArray
        var final = [];
        for (let index = 0; index < saplingArray.length; index++) {
            let element = saplingArray[index];
            let treedata = {
                ...element,
                uploaded: (element.uploaded === 1),
            }
            final.push(treedata);
        }
        //console.log("final shiftTypesObject.value(res.shiftType) live---",  final);

        return { treesInLiveShifts: final, shiftType: shiftTypesObject[res.shiftType] };
    }

    static async fetchSaplingsFromLocalShiftDB(id) {
        let res = await this.localdb.getSaplingsLocalShiftDB(id);
        //console.log("------------fetchSaplingsFromLocalShiftDB------------",res)
        let saplingArray = res.saplingArray
        var final = [];
        for (let index = 0; index < saplingArray.length; index++) {
            let element = saplingArray[index];
            let treedata = {
                ...element,
                uploaded: (element.uploaded === 1),
            }
            final.push(treedata);
        }
        //console.log("final shiftTypesObject.value(res.shiftType) local---", shiftTypesObject[res.shiftType], res.shiftType);
        return { treesInLocalShifts: final, shiftType: shiftTypesObject[res.shiftType] };
    }


    static async fetchTreesFromLocalDB(uploaded = undefined) {
        let res;
        if (uploaded !== undefined) {
            res = await this.localdb.getTreesByUploadStatus(uploaded);
        }
        else {
            res = await this.localdb.getAllTrees();
        }

        //console.log(res);
        var final = [];
        for (let index = 0; index < res.length; index++) {
            let tree = await Utils.formatLocalTreeToJSON(res[index]);
            console.log(tree);
            final.push(tree);
        }
        return final;
    }

    static async formatLocalTreeToJSON(element) {
        // if lat or lng is null, change it to 0
        if (element.lat === 'undefined') {
            element.lat = 0;
        }
        if (element.lng === 'undefined') {
            element.lng = 0;
        }
        //console.log(element.lat, element.lng);
        const userDetailsStr = await AsyncStorage.getItem(Constants.userDetailsKey)
        const userDetails = JSON.parse(userDetailsStr);
        let images = await this.localdb.getTreeImages(element.sapling_id);

        const tree = {
            sapling_id: element.sapling_id,
            plant_type_id: element.plant_type_id,
            plot_id: element.plot_id,
            coordinates: [element.lat, element.lng],
            planted_by: userDetails.name,
            images: images,
            // shiftID: element.shiftID,
            uploaded: (element.uploaded === 1),
            //sequenceNo: element.sequenceNo,
            tree_status: element.tree_status,
            timestamp: element.timestamp
        };
        if (element.uploaded !== undefined) {
            tree.uploaded = (element.uploaded === 1);
        }
        //console.log("treeJSON---", tree);
        tree.user_id = await this.getUserId();
        return tree;
    }

    static async setDBConnection() {
        if (!(this.localdb.db)) {
            await this.localdb.getDBConnection();
        }
        return this.localdb;
    }
    static async treeTypeFromID(treeTypeID) {
        //both ids are numbers of type string.
        const treeNames = await this.localdb.getTreeTypes();
        const requiredTreeType = treeNames.find((tree) => (tree.id === treeTypeID));
        return requiredTreeType;
    }
    static async plotFromPlotID(plotID) {
        //both ids are numbers of type string.
        const plots = await this.localdb.getAllPlots();
        const requiredPlot = plots.find((plot) => (plot.id === plotID));
        console.log(requiredPlot)
        return requiredPlot;
    }
    static async fetchTreeTypesFromLocalDB() {
        let res = await this.localdb.getTreeTypesUsedByLocalTrees();
        return res;
    }

    static async fetchPlotNamesFromLocalDB() {
        let res = await this.localdb.getPlotNamesUsedByLocalTrees();
        return res;
    }

    static async fetchSaplingIdsFromLocalDB() {
        let res = await this.localdb.getSaplingIds();
        return res;
    }


    static async getUserId() {
        let userId = await AsyncStorage.getItem(Constants.userIdKey)
        return parseInt(userId);
    }

    static async getAdminId() {
        return await AsyncStorage.getItem(Constants.adminIdKey);
    }

    static async getLastHash() {
        return await AsyncStorage.getItem(Constants.lastHashKey);
    }

    static async getLastHashForShifts() {
        return await AsyncStorage.getItem(Constants.lastHashForShifts);
    }

    static aspectCalculate() {

        const originalWidth = 720; // maxWidth
        const originalHeight = 960; // maxHeight

        const desiredWidth = 320;
        const desiredHeight = 200;
        const aspectRatio = originalWidth / originalHeight; // Calculate the aspect ratio of the original image

        // Calculate the actual width and height of the displayed image while maintaining the aspect ratio
        let width, height;

        if (desiredWidth / aspectRatio <= desiredHeight) {
            // If the width calculated based on aspect ratio fits within the desired height, use the desired width and calculated height
            width = desiredWidth;
            height = desiredWidth / aspectRatio;
        } else {
            // If the calculated height based on aspect ratio fits within the desired width, use the desired height and calculated width
            width = desiredHeight * aspectRatio;
            height = desiredHeight;
        }

        // Now, you can use the calculated width and height to display the image
        console.log("height:--- ", height, "width:--", width);

    }

    static addTasks() {
        const log = () => console.log('clicking photo');

        ReactNativeForegroundService.add_task(() => log(), {
            delay: 1000,
            onLoop: true,
            taskId: 'taskid',
            onError: e => console.log(`Error logging:`, e),
        });
    }

    static startTask() {
        console.log("--------starting the services------");

        ReactNativeForegroundService.start({
            id: 1244,
            title: 'Foreground Service',
            message: 'We are live World',
            icon: 'ic_launcher',
            button: true,
            button2: true,
            buttonText: 'Button',
            button2Text: 'Anther Button',
            buttonOnPress: 'cray',
            setOnlyAlertOnce: 'true',
            color: '#000000',
            progress: {
                max: 100,
                curr: 50,
            },
        });
    };

    static stopTask() {
        console.log("--------stopping the services------");
        ReactNativeForegroundService.stopAll();
    };

    static async getImage(compressionRequired = false, selectionId) {

        const options = {
            mediaType: 'photo',
            includeBase64: true,
            maxHeight: 960,
            maxWidth: 720,
        };

        try {
            let response = {}
            if (selectionId === 0) {
                response = await launchCamera(options);
            } else {
                response = await launchImageLibrary(options)
            }


            if (response.didCancel) {
                console.log('User cancelled image picker');
            } else if (response.error) {
                console.log('ImagePicker Error: ', response.error);
            } else {

                const timestamp = new Date().toISOString(); // only show time and not date
                let filesz = response.assets[0].fileSize;
                let base64Data = response.assets[0].base64;



                let imagePath = response.assets[0].uri;

                console.log("response.assets[0]----", filesz);

                if (compressionRequired) {
                    const compressedData = await Utils.compressImageAt(filesz, imagePath);
                    //console.log("compressedData: ", compressedData.size);
                    if (compressedData) {
                        base64Data = compressedData;
                    } else {
                        console.log("could not compressed------");
                    }
                }
                const newImage = {
                    data: base64Data,
                    meta: {
                        capturetimestamp: timestamp,
                        remark: Strings.messages.defaultRemark,

                    },
                };

                return newImage;
            }
        } catch (error) {
            console.log('An error occurred while accessing the camera:', error);
            const stackTrace = error.stack;
            const errorLog = {
                msg: "Error occurred while accessing the camera (inside Utils)",
                error: JSON.stringify(error),
                stackTrace: stackTrace
            };
            await this.logException(JSON.stringify(errorLog));
            return null;
        }

        //return { newImage: newImage, imageForModal: imageForModal };


    }



    static async formatImageForSapling(image, saplingid) {
        //console.log("image---", image);
        let newImage = { ...image }
        newImage.saplingid = saplingid;
        const timestamp = newImage.meta.capturetimestamp;
        const imageName = `${saplingid}_${timestamp}.jpg`;
        newImage.name = imageName;
        newImage.size = newImage.size
        return newImage;
    }

    static async compressImageAt(filesz, imagePath) {
        console.log("Original file size:", filesz);
        const maxsz = 1024 * 900; // 900 KB 

        if (filesz > maxsz) {
            console.log("File size exceeds maxsz:", maxsz);

            // Initialize quality parameters
            let minQuality = 1; // Minimum quality
            let maxQuality = 100; // Maximum quality
            let compressedQuality = 100; // Initial quality

            // Binary search to find optimal quality
            while (maxQuality - minQuality > 1) {
                compressedQuality = Math.floor((minQuality + maxQuality) / 2);

                // Compress the image
                const resizedImage = await ImageResizer.createResizedImage(
                    imagePath,
                    960, // Target width
                    720, // Target height
                    'JPEG', // Format
                    compressedQuality // Quality
                );

                const resizedImageSize = resizedImage.size;
                console.log("resizedImage----:", resizedImageSize);



                if (resizedImageSize > maxsz) {
                    // Image size is still too large, reduce quality
                    maxQuality = compressedQuality;
                } else {
                    // Image size is within limits, increase quality
                    minQuality = compressedQuality;
                }
            }

            // Final compressed image
            const finalResizedImage = await ImageResizer.createResizedImage(
                imagePath,
                960, // Target width
                720, // Target height
                'JPEG', // Format
                minQuality // Final quality
            );

            const finalResizedImagePath = finalResizedImage.uri;

            try {
                // Read the final compressed image file as base64
                const base64Data = await RNFS.readFile(finalResizedImagePath, 'base64');
                console.log("Final resized image:", finalResizedImage.size);
                console.log('Off factor:', maxsz / finalResizedImage.size);
                return base64Data;
            } catch (error) {
                // Handle any errors while reading the file
                console.error('Error reading file:', error);
                const stackTrace = error.stack;
                const errorLog = {
                    msg: "Error occurred while trying to read base64 image file (inside Utils)",
                    error: JSON.stringify(error),
                    stackTrace: stackTrace
                };
                await this.logException(JSON.stringify(errorLog));
                return null; // Return null if there's an error
            }
        }

        return null; // Return null if file size is already within limit
    }


}



export class Constants {
    static userIdKey = 'userid';
    static userRole = 'user_role';
    static authToken = 'token';
    static userDetailsKey = 'userobj';
    static adminIdKey = 'adminid';
    static phoneNumber = 'phoneNo';
    static lastHashKey = 'lasthash';
    static lastHashForShifts = 'lasthashshift';
    static hashForPlotSaplingsKey = 'hashForPlotSaplings';
    static appRootTagKey = 'rootTag';
    static syncDateKey = 'date';
    static treeFormTemplateData = { inSaplingId: null, inLat: 0, inLng: 0, inImage: null, inPlot: null, inTreeType: null, inUserId: 0, inTreeStatus: 'alive' }
    static selectedLangKey = 'LANG';
    static selectedTheme = 'DARK';
    static authToken = 'token'
    static userRole = 'user_role'
    static logoImage() {
        return require('../../assets/14-trees-logo.png');
    }
    static placeholderImage() {
        return require('../../assets/icon-profile.png');
    }

    // helpers data
    static lastTreesFetchedAt = 'last_trees_fetched_at'
    static lastUsersFetchedAt = 'last_users_fetched_at'
    static lastPlotsFetchedAt = 'last_plots_fetched_at'
    static lastSitesFetchedAt = 'last_sites_fetched_at'
}

export const getImageSourceObject = (src) => {
    if (src.length === 0) {
        return Constants.placeholderImage();
    }
    else if (src.startsWith('http')) {
        return { uri: src }
    }
    console.log('image src was unexpected.')
    return Constants.placeholderImage()
}
