import { View, Text, Modal, StyleSheet, Dimensions, ScrollView, Image, Alert } from 'react-native';
import React, { useState, useEffect, useContext, useCallback } from 'react';
import { Utils, Constants } from '../services/Utils';
import { Strings } from '../services/Strings';
import GlobalContext from '../context/GlobalContext ';
import { treeFormModes } from './TreeForm';
import { CustomButtonStyles, commonStyles, customModalStyles } from '../services/Styles';
import { CustomDropdown } from './CustomDropdown';
import { stackNavRef } from '../App';
import { Button } from 'react-native-paper';
import { shiftTypes } from '../screens/Shifts';



const PlotSelectModal = ({ plotModalVisible, setPlotModalVisible, mode, onFetchData }) => {
    const { setShiftDone, setTreesPlanted, treesPlanted, plotSelected, shiftType, setPlotSelected, shiftID, setShiftID, lightTheme } = useContext(GlobalContext);

    const [plotItems, setPlotItems] = useState([]); //for plots


    const fetchDetails = async () => {
        let { plots } = await Utils.getLocalTreeTypesAndPlots();
        setPlotItems(plots);
    };

    useEffect(() => {
        if (plotModalVisible) {
            fetchDetails();
        }

    }, [plotModalVisible]);


    async function handlePlotChanges(cancel) {

        if (mode === treeFormModes.startShift) {
            if (cancel === 0) {
                setPlotSelected(null);
                setPlotModalVisible(false);
                return;
            } else {

                if (plotSelected === null) {
                    Alert.alert(Strings.alertMessages.NoPlotSelected, Strings.alertMessages.SelectPlot);
                    return;
                }

                if (shiftType === shiftTypes.addSapling) {
                    stackNavRef.current?.navigate(
                        Strings.screenNames.getString('AddTreeShift', Strings.english),
                    );
                } else {
                    stackNavRef.current?.navigate(
                        Strings.screenNames.getString('AddImageShift', Strings.english),
                    );
                }

                setPlotModalVisible(false);
                setShiftDone(false);

                let shiftData, autoGeneratedShiftId;

                shiftData = {
                    shifttype: shiftType === shiftTypes.addSapling ? 'addSapling' : 'addImage',
                    user_id: await Utils.getUserId(),
                    plotselected: plotSelected.name,
                    shiftended: 0,
                    shiftuploadcomplete: 0,
                    starttime: Utils.getCurrentTime12Hr(),
                    endtime: Utils.getCurrentTime12Hr(),
                    timetaken: 0,
                    treesplanted: 0
                }

                console.log("starting shift and inserting into shift table--", shiftData);
                autoGeneratedShiftId = await Utils.saveShiftsToLocalDB(shiftData);


                setShiftID(autoGeneratedShiftId);
            }

        }
        else {
            if (plotSelected === null) {
                Alert.alert(Strings.alertMessages.NoPlotSelected, Strings.alertMessages.SelectPlot);
                return;
            }
            setPlotModalVisible(false);
            
            await Utils.changeShiftPlot(plotSelected.name, shiftID);
            
            if (shiftType === shiftTypes.addSapling) {
                console.log("'----------changing plot--in add sapling shift type---")
                await Utils.updateTreesWithChangedPlot(plotSelected.value, shiftID);
                onFetchData()
            }
        }
    }

    return (
        <Modal
            animationType="slide"
            transparent={true}
            visible={
                plotModalVisible
            }
            onRequestClose={() => handlePlotChanges(0)}
        >
            <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ ...customModalStyles.plotSelectScrollView, marginTop: mode === treeFormModes.plotChange ? 205 : 80 }}>
                <View style={{
                    height: '100%',
                    backgroundColor: 'white',
                    //borderRadius: 0,
                    //padding: 35,
                    alignItems: 'center',
                    shadowColor: '#000',
                    shadowOffset: {
                        width: 0,
                        height: 2,
                    }
                }} >
                    <View style={{
                        backgroundColor: 'white',
                        padding: 2,
                        margin: 10,
                        //borderRadius: 10, borderColor: '#ccc', borderWidth: ,
                        width: '98%'
                    }}>
                        <Text style={{
                            ...commonStyles.textSync, color: lightTheme ? '#52525C' : 'black',
                            margin: 20, fontSize: 22, marginBottom: 10

                        }}>{Strings.messages.EnterPlotName}</Text>
                        <View style={{ flexDirection: "row" }}>
                            <Text style={{
                                ...commonStyles.textSync, color: lightTheme ? '#52525C' : 'black',
                                marginHorizontal: 20, fontSize: 18, marginBottom: 10

                            }}>{Strings.messages.ShiftType}</Text>
                            <Image
                                source={shiftType === 0 ? require('../../assets/icon-sprout.png') : require('../../assets/icon-bw-camera.png')}
                                style={{
                                    height: 25, width: 25
                                }}
                            />
                            <Text style={{
                                fontSize: 20,
                                fontFamily: 'Inter-Regular',
                                color: 'black',
                                fontWeight: '600', color: lightTheme ? '#52525C' : 'black',
                                marginHorizontal: 5, fontSize: 18, marginBottom: 10

                            }}>{shiftType === 0 ? Strings.buttonLabels.AddNewTree : Strings.buttonLabels.AddImage}</Text>
                        </View>

                        <View style={{ margin: 8, marginTop: 0 }}>
                            <CustomDropdown
                                initItem={plotSelected}
                                items={plotItems}
                                label={Strings.labels.SelectPlot}
                                onSelectItem={(item) => {
                                    console.log("------plot item got-----", item);
                                    setPlotSelected(item);
                                }}
                            />
                        </View>

                        <View style={{ ...CustomButtonStyles.container }}>
                            <View style={{ ...CustomButtonStyles.buttonRow, }}>
                                <View style={CustomButtonStyles.buttonContainer}>
                                    <Button
                                        onPress={() => handlePlotChanges(0)}
                                        mode="elevated"
                                        buttonColor='red'
                                        labelStyle={CustomButtonStyles.buttonLabel}
                                        style={CustomButtonStyles.button}
                                    >
                                        {Strings.buttonLabels.cancel}
                                    </Button>
                                </View>
                                <View style={CustomButtonStyles.buttonContainer}>
                                    <Button
                                        onPress={() => handlePlotChanges(1)}
                                        //mode="elevated"
                                        buttonColor="#1D4ED8"
                                        labelStyle={CustomButtonStyles.buttonLabel}
                                        style={{ ...CustomButtonStyles.button }}
                                    >
                                        {Strings.buttonLabels.Submit}
                                    </Button>
                                </View>
                            </View>
                        </View>

                    </View>
                </View>
            </ScrollView>
        </Modal >
    )


};

export default PlotSelectModal;