import { View, Text, Modal, ScrollView, Alert, Image } from 'react-native';
import React, { useState, useEffect, useContext } from 'react';
import { Utils, Constants } from '../services/Utils';
import { Strings } from '../services/Strings';
import GlobalContext from '../context/GlobalContext ';
import { treeFormModes } from './TreeForm';
import { CustomButtonStyles, commonStyles, customModalStyles } from '../services/Styles';
import { CustomDropdown } from './CustomDropdown';
import { stackNavRef } from '../App';
import { Button } from 'react-native-paper';
import { shiftTypes } from '../screens/Shifts';
import Icon from 'react-native-vector-icons/Ionicons';


function UpdatePlotSelectModal({ updatePlotModalVisible, setUpdatePlotModalVisible, mode, onFetchData }) {
    const { newPlotSelected, setNewPlotSelected, setShiftDone, plotSelected, shiftType, setPlotSelected, shiftID, setShiftID, lightTheme } = useContext(GlobalContext);

    const [plotItems, setPlotItems] = useState([]); //for plots

    const fetchDetails = async () => {
        let { plots } = await Utils.getLocalTreeTypesAndPlots();
        setPlotItems(plots);
    };

    useEffect(() => {
        if (updatePlotModalVisible) {
            fetchDetails();
        }

    }, [updatePlotModalVisible]);


    async function handlePlotChanges(cancel) {

        if (mode === treeFormModes.startShift) {
            if (cancel === 0) {
                setPlotSelected(null);
                setNewPlotSelected(null);
                setUpdatePlotModalVisible(false);
                return;
            } else {

                if (plotSelected === null || newPlotSelected === null) {
                    Alert.alert(Strings.alertMessages.NoPlotSelected, Strings.alertMessages.SelectPlot);
                    return;
                }

                if (plotSelected.name === newPlotSelected.name) {
                    Alert.alert(Strings.alertMessages.NoPlotSelected, Strings.alertMessages.SelectDifferentPlot);
                    return;
                }

                if (shiftType === shiftTypes.updatePlot) {
                    stackNavRef.current?.navigate(
                        Strings.screenNames.getString('UpdatePlotShift', Strings.english),
                    );
                }

                setUpdatePlotModalVisible(false);
                setShiftDone(false);

                let shiftData, autoGeneratedShiftId;

                if (shiftType === shiftTypes.updatePlot) {
                    shiftData = {
                        shifttype: 'updatePlot',
                        user_id: await Utils.getUserId(),
                        plotselected: plotSelected.name,
                        shiftended: 0,
                        shiftuploadcomplete: 0,
                        starttime: Utils.getCurrentTime12Hr(),
                        endtime: Utils.getCurrentTime12Hr(),
                        timetaken: 0,
                        treesplanted: 0
                    }

                    console.log("starting shift and inserting into shift table--", shiftData);
                    autoGeneratedShiftId = await Utils.saveShiftsToLocalDB(shiftData);
                }

                setShiftID(autoGeneratedShiftId);
            }

        }
        else {
            console.log("changing plot-----", cancel);

            if (plotSelected === null || newPlotSelected === null) {
                Alert.alert(Strings.alertMessages.NoPlotSelected, Strings.alertMessages.SelectPlot);
                return;
            }

            if (plotSelected.name === newPlotSelected.name) {
                Alert.alert(Strings.alertMessages.NoPlotSelected, Strings.alertMessages.SelectDifferentPlot);
                return;
            }

            await Utils.changeShiftPlot(plotSelected.name, shiftID);
            await Utils.updateTreesWithChangedPlotInPlotsTable(plotSelected.value, newPlotSelected.value, shiftID);

            setUpdatePlotModalVisible(false);
            onFetchData();
        }
    }

    return (
        <Modal
            animationType="slide"
            transparent={true}
            visible={
                updatePlotModalVisible
            }
            onRequestClose={() => handlePlotChanges(0)}
        >
            <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ ...customModalStyles.plotSelectScrollView, marginTop: mode === treeFormModes.plotChange ? 205 : 80 }}>
                <View style={{
                    height: '100%',
                    backgroundColor: 'white',
                    //borderRadius: 0,
                    //padding: 35,
                    alignItems: 'center',
                    shadowColor: '#000',
                    shadowOffset: {
                        width: 0,
                        height: 2,
                    }
                }}>
                    <View style={{
                        backgroundColor: 'white',
                        padding: 2,
                        margin: 5,
                        //borderRadius: 10, borderColor: '#ccc', borderWidth: ,
                        width: '98%'
                    }}>

                        <View style={{
                            ...commonStyles.textSync, color: lightTheme ? '#52525C' : 'black',
                            margin: 5, fontSize: 22, marginBottom: 20

                        }}>
                            <Text style={{
                                ...commonStyles.textSync, color: lightTheme ? '#52525C' : 'black',
                                margin: 20, fontSize: 22, marginBottom: 10
                            }}>
                                {Strings.messages.StartThisShift}</Text>
                            <View style={{ flexDirection: "row" }}>
                                <Text style={{
                                    ...commonStyles.textSync, color: lightTheme ? '#52525C' : 'black',
                                    marginHorizontal: 20, fontSize: 17, marginBottom: 10

                                }}>{Strings.messages.ShiftType}</Text>
                                <Image
                                    source={require('../../assets/icon-land.png')}
                                    style={{
                                        height: 25, width: 25
                                    }}
                                />
                                <Text style={{
                                    fontSize: 20,
                                    fontFamily: 'Inter-Regular',
                                    color: 'black',
                                    fontWeight: '600', color: lightTheme ? '#52525C' : 'black',
                                    marginHorizontal: 5, fontSize: 18, marginBottom: 10

                                }}>{Strings.buttonLabels.UpdatePlot}</Text>
                            </View>
                            <Text style={customModalStyles.textView(lightTheme)}>{Strings.messages.OldPlotName}</Text>
                            <CustomDropdown
                                initItem={plotSelected}
                                items={plotItems}
                                label={Strings.labels.SelectPlot}
                                onSelectItem={(item) => {
                                    console.log("------old plot item got-----", item);
                                    setPlotSelected(item);
                                }}
                            />
                        </View>

                        <View style={{
                            width: 33, height: 33, alignSelf: "center", alignItems: "center", paddingTop: 3, borderRadius: 38, backgroundColor: "green", shadowColor: '#000', marginBottom: -5,
                            shadowColor: 'black',
                            shadowOffset: { width: 0, height: 2 },
                            shadowOpacity: 0.5, // Adjust this value
                            elevation: 5,
                        }}>
                            <Icon name="arrow-down" size={26} color="white" />
                        </View>

                        <View style={{
                            ...commonStyles.textSync, color: lightTheme ? '#52525C' : 'black',
                            margin: 5, fontSize: 22, marginBottom: 10, marginTop: 10,

                        }}>
                            <Text style={customModalStyles.textView(lightTheme)}>{Strings.messages.NewPlotName}</Text>
                            <CustomDropdown
                                initItem={newPlotSelected}
                                items={plotItems}
                                label={Strings.labels.SelectPlot}
                                onSelectItem={(item) => {
                                    console.log("------new plot item got-----", item);
                                    setNewPlotSelected(item);
                                }}
                            />
                        </View>

                        <View style={{ ...CustomButtonStyles.container, }}>
                            <View style={{
                                flexDirection: 'row',
                                marginHorizontal: 22,
                                marginTop: 15,
                                marginBottom: 10,
                                backgroundColor: "white"
                            }}>
                                <View style={{
                                    ...CustomButtonStyles.buttonContainer, shadowColor: 'black'
                                }}>
                                    <Button
                                        onPress={() => handlePlotChanges(0)}
                                        mode="elevated"
                                        buttonColor='red'
                                        labelStyle={CustomButtonStyles.buttonLabel}
                                        style={CustomButtonStyles.button}
                                    >
                                        {Strings.buttonLabels.cancel}
                                    </Button>
                                </View>
                                <View style={CustomButtonStyles.buttonContainer}>
                                    <Button
                                        onPress={() => handlePlotChanges(1)}
                                        mode="elevated"
                                        buttonColor='#1D4ED8'
                                        labelStyle={CustomButtonStyles.buttonLabel}
                                        style={CustomButtonStyles.button}
                                    >
                                        {Strings.buttonLabels.Submit}
                                    </Button>
                                </View>
                            </View>
                        </View>
                    </View>
                </View>
            </ScrollView>
        </Modal >
    )
}

export default UpdatePlotSelectModal