import { View, Text, Modal, StyleSheet, Dimensions, ScrollView, ToastAndroid, Alert } from 'react-native';
import React, { useState, useEffect, useContext, useCallback } from 'react';
import { Utils, Constants } from '../services/Utils';
import { Strings } from '../services/Strings';
import GlobalContext from '../context/GlobalContext ';
import { treeFormModes } from './TreeForm';
import { CustomButtonStyles, commonStyles, customModalStyles } from '../services/Styles';
import { CustomDropdown } from './CustomDropdown';
import { stackNavRef } from '../App';
import { Button } from 'react-native-paper';
import { shiftTypes } from '../screens/Shifts';


function UpdatePlotSelectModal({ updatePlotModalVisible, setUpdatePlotModalVisible, mode, onFetchData }) {
    const { newPlotSelected, setNewPlotSelected, setShiftDone, setTreesPlanted, treesPlanted, plotSelected, shiftType, setPlotSelected, shiftID, setShiftID, lightTheme } = useContext(GlobalContext);

    const [plotItems, setPlotItems] = useState([]); //for plots

    const fetchDetails = async () => {
        let { plots } = await Utils.getLocalTreeTypesAndPlots();
        setPlotItems(plots);
    };

    useEffect(() => {
        console.log("-------------in PlotSelect-------------", shiftType)
        if (updatePlotModalVisible) {
            fetchDetails();
        }

    }, [updatePlotModalVisible]);


    async function handlePlotChanges(cancel) {

        if (mode === treeFormModes.startShift) {
            if (cancel === 0) {
                setPlotSelected(null);
                setNewPlotSelected(null);
                setUpdatePlotModalVisible(false);
                return;
            } else {

                if (plotSelected === null || newPlotSelected === null) {
                    Alert.alert(Strings.alertMessages.NoPlotSelected, Strings.alertMessages.SelectPlot);
                    return;
                }

                if (plotSelected.name === newPlotSelected.name) {
                    Alert.alert(Strings.alertMessages.NoPlotSelected, Strings.alertMessages.SelectDifferentPlot);
                    return;
                }

                if (shiftType === shiftTypes.updatePlot) {
                    stackNavRef.current?.navigate(
                        Strings.screenNames.getString('UpdatePlot', Strings.english),
                    );
                }

                setUpdatePlotModalVisible(false);
                setShiftDone(false);

                let shiftData, autoGeneratedShiftId;

                if (shiftType === shiftTypes.updatePlot) {
                    shiftData = {
                        shifttype: 'updatePlot',
                        user_id: await Utils.getUserId(),
                        plotselected: plotSelected.name,
                        shiftended: 0,
                        shiftuploadcomplete: 0,
                        starttime: Utils.getCurrentTime12Hr(),
                        endtime: Utils.getCurrentTime12Hr(),
                        timetaken: 0,
                        treesplanted: 0
                    }

                    console.log("starting shift and inserting into shift table--", shiftData);
                    autoGeneratedShiftId = await Utils.saveShiftsToLocalDB(shiftData);
                }

                setShiftID(autoGeneratedShiftId);
            }

        }
        else {
            console.log("changing plot-----" , cancel);
            if (plotSelected === null || newPlotSelected === null) {
                Alert.alert(Strings.alertMessages.NoPlotSelected, Strings.alertMessages.SelectPlot);
                return;
            }

            await Utils.updateTreesWithChangedPlot(plotSelected.value, shiftID); //wrong logic inside tree db

            setUpdatePlotModalVisible(false);
            onFetchData();
        }
    }

    return (
        <Modal
            animationType="slide"
            transparent={true}
            visible={
                updatePlotModalVisible //changesNeeded
            }
            onRequestClose={() => handlePlotChanges(0)} // Add this line
        >
            <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ ...customModalStyles.plotSelectScrollView }}>
                <View style={customModalStyles.plotSelectOuterView}>
                    <View style={customModalStyles.plotSelectView}>

                        <View style={{ margin: 8, marginTop: 0 }}>
                            <Text style={customModalStyles.textView(lightTheme)}>{Strings.messages.OldPlotName}</Text>
                            <CustomDropdown
                                initItem={plotSelected}
                                items={plotItems}
                                label={Strings.labels.SelectPlot}
                                onSelectItem={(item) => {
                                    console.log("------old plot item got-----", item);
                                    setPlotSelected(item);
                                }}
                            />
                        </View>


                        <View style={{ margin: 8, marginTop: 0 }}>
                            <Text style={customModalStyles.textView(lightTheme)}>{Strings.messages.NewPlotName}</Text>
                            <CustomDropdown
                                initItem={newPlotSelected}
                                items={plotItems}
                                label={Strings.labels.SelectPlot}
                                onSelectItem={(item) => {
                                    console.log("------new plot item got-----", item);
                                    setNewPlotSelected(item);
                                }}
                            />
                        </View>

                        <View style={CustomButtonStyles.container}>
                            <View style={CustomButtonStyles.buttonRow}>
                                <View style={CustomButtonStyles.buttonContainer}>
                                    <Button
                                        onPress={() => handlePlotChanges(0)}
                                        mode="contained"
                                        buttonColor='red'
                                        labelStyle={CustomButtonStyles.buttonLabel}
                                        style={CustomButtonStyles.button}
                                    >
                                        {Strings.buttonLabels.cancel}
                                    </Button>
                                </View>
                                <View style={CustomButtonStyles.buttonContainer}>
                                    <Button
                                        onPress={() => handlePlotChanges(1)}
                                        mode="contained"
                                        buttonColor='#1D4ED8'
                                        labelStyle={CustomButtonStyles.buttonLabel}
                                        style={CustomButtonStyles.button}
                                    >
                                        {Strings.buttonLabels.Submit}
                                    </Button>
                                </View>
                            </View>
                        </View>

                    </View>
                </View>
            </ScrollView>
        </Modal>
    )
}

export default UpdatePlotSelectModal